### PR TITLE
Some little changes per Visual Studio compatible

### PR DESCRIPTION
**Pull request by BDisp**
Check https://stackoverflow.com/questions/55459078/cmake-cannot-open-file-optimized-lib-when-trying-to-add-boost-process?answertab=votes#tab-top

### CODE REVIEW

**Comment by paolo-projects** [comment]
the cmake and services error stuff is ok (the services error messages should be worked out a little better but I have no time atm) but the *system("pause")* would produce a command not found on linux machines. I think a getchar fits well instead

**Comment by BDisp** [comment]
Ok it's up to you when you have the time. Note that I updated the DrDonk version for linux compatibility.

**Comment by BDisp** [comment]
Hi @paolo-projects, I needed to talk to you in private, could you give me your email contact please? Thanks.

**Comment by paolo-projects** [comment]
Hi, I can't write it here where anyone can see it (it would be flooded with spam). You can however contact me on discord at Paolo#4013

**Comment by BDisp** [comment]
@paolo-projects thanks. I already sent you a request

**Pull request merged**
