### PR TITLE
Don't test the total number of bytes to be downloaded in curl progress callback

### PR DESCRIPTION
**Pull request by pzhlkj6612**
Hi. Please see commit message for details.

Note that the three commits belonging to this PR should **not** be squashed into one commit.

### CODE REVIEW

**Comment by pzhlkj6612** [comment]
Hi @paolo-projects , could I ask you why these PRs were closed? Is there something I was missing or doing wrong?

**Comment by paolo-projects** [comment]
Hey @pzhlkj6612, I apologize for not giving an explanation.

You make a good point in this pull request, but I was already planning on refactoring some of the code. Now in addition to the blank lines a message informing of the tools not found at the provided link is printed.
Additionally, a GUI is being added to the Windows target through the win32 api, it will be available as soon as I push the changes. The linux target will still be using the shell but it will have colored output for better recognition of errors.

If you're willing to help, any contribution is highly appreciated.

**Comment by pzhlkj6612** [comment]
Hi @paolo-projects , thanks for your reply!

> Now in addition to the blank lines a message informing of the tools not found at the provided link is printed.

I haven't read the code in this repository for a long time, so I didn't know that you made the output better.

> Additionally, a GUI is being added to the Windows target through the win32 api, it will be available as soon as I push the changes.

GUI on Windows is awesome! Do you have any plans to make the program work in both GUI and CLI?

> If you're willing to help, any contribution is highly appreciated.

Ah, thank you! But unfortunately, I'm too busy to dig into this at the moment. I'll take a look when I'm free.

**Comment by paolo-projects** [comment]
> GUI on Windows is awesome! Do you have any plans to make the program work in both GUI and CLI?

I don't think so, it would be a mess, better to keep it simple. Windows users are accustomed to using a gui as much as Linux users are to the shell.

> Ah, thank you! But unfortunately, I'm too busy to dig into this at the moment. I'll take a look when I'm free.

No problem, I understand there's new stuff added and refactoring of old code, let me know if I can be of help.

**Pull request closed without merging**
